version: "1"

services:
  - type: web
    name: setpoint-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        fromService:
          type: web
          name: setpoint-client
          property: url
  - type: web
    name: setpoint-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        fromService:
          type: web
          name: setpoint-api
          property: url
      - key: VITE_SOCKET_URL
        fromService:
          type: web
          name: setpoint-api
          property: url
