version: "1"

services:
  - type: web
    name: scorebugger-api
    plan: free
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MONGODB_URI_PROD
        sync: false
      - key: MONGODB_URI_DEV
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
  - type: web
    name: scorebugger-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: VITE_API_URL
        sync: false
      - key: VITE_SOCKET_URL
        sync: false
